

export const WORD_CATEGORIES: { [key: string]: string[] } = {
    "Aleatorio": [],
    "Comida": ["Pizza", "Sushi", "Taco", "Hamburguesa", "Paella", "Ensalada", "Pasta", "Helado", "Sopa", "Queso", "Croissant", "Sándwich", "Cereal", "Yogur", "Chocolate", "Galleta", "Café", "Té", "Jugo", "Vino", "Manzana", "Plátano", "Naranja", "Fresa", "Uva", "Sandía", "Melón", "Piña", "Mango", "Pera", "Cereza", "Limón", "Aguacate", "Brócoli", "Zanahoria", "Papa", "Cebolla", "Ajo", "Tomate", "Lechuga", "Pepino", "Pimiento", "Maíz", "Arroz", "Frijoles", "Lentejas", "Garbanzos", "Pollo", "Carne", "Pescado", "Huevo", "Leche", "Mantequilla", "Pan", "Tostada", "Mermelada", "Miel", "Azúcar", "Sal", "Pimienta", "Aceite", "Vinagre", "Mostaza", "Ketchup", "Mayonesa", "Pastel", "Flan", "Gelatina", "Dona", "Muffin", "Panqueque", "Waffle", "Palomitas", "Nueces", "Almendras", "Pistachos", "Avellanas", "Cacahuates", "Refresco", "Agua", "Cerveza", "Salsa", "Guacamole", "Chilaquiles", "Pozole", "Mole", "Ceviche", "Empanada", "Arepa", "Feijoada", "Asado", "Churros", "Tiramisú", "Lasaña", "Risotto", "Goulash", "Kebab", "Falafel", "Hummus", "Croqueta", "Gazpacho"],
    "Animales": ["Perro", "Gato", "León", "Elefante", "Jirafa", "Tigre", "Oso", "Pez", "Pájaro", "Serpiente", "Caballo", "Cebra", "Pingüino", "Delfín", "Ballena", "Mono", "Loro", "Búho", "Rana", "Mariposa", "Vaca", "Cerdo", "Oveja", "Cabra", "Gallina", "Pato", "Ganso", "Pavo", "Conejo", "Ratón", "Hámster", "Ardilla", "Zorro", "Lobo", "Coyote", "Ciervo", "Alce", "Reno", "Hipopótamo", "Rinoceronte", "Cocodrilo", "Caimán", "Tortuga", "Lagarto", "Iguana", "Camaleón", "Koala", "Canguro", "Panda", "Gorila", "Chimpancé", "Orangután", "Murciélago", "Erizo", "Topo", "Castor", "Nutria", "Morsa", "Foca", "Leopardo", "Guepardo", "Hiena", "Suricata", "Llama", "Alpaca", "Vicuña", "Armadillo", "Perezoso", "Oso hormiguero", "Tucán", "Colibrí", "Flamenco", "Cisne", "Águila", "Halcón", "Cuervo", "Paloma", "Avestruz", "Emú", "Pulpo", "Calamar", "Medusa", "Estrella de mar", "Cangrejo", "Langosta", "Camarón", "Caracol", "Babosa", "Gusano", "Araña", "Escorpión", "Abeja", "Avispa", "Hormiga", "Mosca", "Mosquito", "Libélula", "Grillo", "Saltamontes"],
    "Lugares": ["Playa", "Montaña", "Ciudad", "Bosque", "Desierto", "Oficina", "Escuela", "Restaurante", "Parque", "Museo", "Aeropuerto", "Estación", "Gimnasio", "Teatro", "Banco", "Granja", "Fábrica", "Castillo", "Puerto", "Universidad", "Hospital", "Farmacia", "Supermercado", "Tienda", "Centro comercial", "Cine", "Biblioteca", "Iglesia", "Templo", "Mezquita", "Sinagoga", "Cementerio", "Estadio", "Piscina", "Zoológico", "Acuario", "Jardín", "Plaza", "Calle", "Avenida", "Carretera", "Puente", "Túnel", "Río", "Lago", "Mar", "Océano", "Isla", "Volcán", "Cueva", "Cascada", "Valle", "Colina", "Pradera", "Selva", "Sabana", "Pantano", "Glaciar", "Polo Norte", "Polo Sur", "Casa", "Apartamento", "Edificio", "Hotel", "Motel", "Hostal", "Cabaña", "Palacio", "Prisión", "Cuartel", "Embajada", "Consulado", "Ayuntamiento", "Tribunal", "Congreso", "Senado", "Laboratorio", "Observatorio", "Planetario", "Galería de arte", "Ópera", "Circo", "Feria", "Discoteca", "Bar", "Cafetería", "Panadería", "Pastelería", "Carnicería", "Pescadería", "Frutería", "Verdulería", "Mercado", "Peluquería", "Barbería", "Spa", "Taller", "Garaje", "Gasolinera"],
    "Profesiones": ["Médico", "Profesor", "Bombero", "Policía", "Ingeniero", "Artista", "Chef", "Científico", "Piloto", "Abogado", "Actor", "Músico", "Escritor", "Pintor", "Deportista", "Periodista", "Juez", "Mecánico", "Cocinero", "Veterinario", "Enfermero", "Dentista", "Farmacéutico", "Psicólogo", "Psiquiatra", "Cirujano", "Pediatra", "Cardiólogo", "Dermatólogo", "Oftalmólogo", "Arquitecto", "Diseñador", "Programador", "Analista", "Contador", "Economista", "Administrador", "Gerente", "Director", "Presidente", "Secretario", "Recepcionista", "Asistente", "Traductor", "Intérprete", "Guía turístico", "Agente de viajes", "Azafata", "Marino", "Soldado", "Militar", "Detective", "Guardia", "Vigilante", "Salvavidas", "Paramédico", "Carpintero", "Albañil", "Electricista", "Fontanero", "Jardinero", "Agricultor", "Ganadero", "Pescador", "Minero", "Leñador", "Panadero", "Pastelero", "Carnicero", "Pescadero", "Frutero", "Verdulero", "Florista", "Cajero", "Vendedor", "Comerciante", "Empresario", "Banquero", "Corredor de bolsa", "Agente inmobiliario", "Camarero", "Barman", "Sommelier", "Fotógrafo", "Camarógrafo", "Director de cine", "Productor", "Editor", "Sonidista", "Iluminador", "Maquillador", "Peluquero", "Estilista", "Modelo", "Bailarín", "Cantante", "Compositor", "DJ", "Poeta", "Novelista", "Escultor", "Filósofo"],
    "Deportes": ["Fútbol", "Baloncesto", "Tenis", "Natación", "Béisbol", "Golf", "Boxeo", "Ciclismo", "Voleibol", "Atletismo", "Rugby", "Hockey", "Críquet", "Esquí", "Surf", "Patinaje", "Lucha", "Gimnasia", "Karate", "Judo", "Taekwondo", "Kung Fu", "Aikido", "Kendo", "Sumo", "Esgrima", "Tiro con arco", "Tiro deportivo", "Halterofilia", "Fisicoculturismo", "Crossfit", "Yoga", "Pilates", "Zumba", "Aeróbic", "Baile deportivo", "Patinaje artístico", "Patinaje de velocidad", "Skateboarding", "BMX", "Motocross", "Automovilismo", "Motociclismo", "Rally", "Fórmula 1", "Nascar", "Vela", "Remo", "Piragüismo", "Kayak", "Esquí acuático", "Wakeboard", "Windsurf", "Kitesurf", "Buceo", "Snorkel", "Apnea", "Waterpolo", "Nado sincronizado", "Saltos", "Triatlón", "Pentatlón", "Decatlón", "Maratón", "Carrera de vallas", "Salto de altura", "Salto con pértiga", "Salto de longitud", "Lanzamiento de peso", "Lanzamiento de disco", "Lanzamiento de martillo", "Lanzamiento de jabalina", "Balonmano", "Fútbol sala", "Fútbol americano", "Lacrosse", "Polo", "Equitación", "Bádminton", "Squash", "Raquetbol", "Pádel", "Tenis de mesa", "Billar", "Snooker", "Bolos", "Dardos", "Ajedrez", "Damas", "Go", "Póker", "Bridge", "Escalada", "Alpinismo", "Senderismo", "Parkour", "Paracaidismo", "Ala delta", "Parapente"],
    "Objetos": ["Teléfono", "Silla", "Mesa", "Libro", "Coche", "Reloj", "Gafas", "Llave", "Botella", "Ordenador", "Mochila", "Paraguas", "Lámpara", "Espejo", "Tijeras", "Martillo", "Clavo", "Tornillo", "Cepillo", "Peine", "Cama", "Sofá", "Armario", "Estantería", "Escritorio", "Puerta", "Ventana", "Cortina", "Alfombra", "Cojín", "Manta", "Almohada", "Toalla", "Jabón", "Champú", "Pasta de dientes", "Cepillo de dientes", "Papel higiénico", "Plato", "Vaso", "Taza", "Cubiertos", "Tenedor", "Cuchillo", "Cuchara", "Olla", "Sartén", "Nevera", "Horno", "Microondas", "Lavadora", "Secadora", "Aspiradora", "Plancha", "Televisión", "Radio", "Altavoz", "Auriculares", "Cámara", "Micrófono", "Teclado", "Ratón", "Impresora", "Escáner", "Bolígrafo", "Lápiz", "Cuaderno", "Papel", "Goma de borrar", "Sacapuntas", "Regla", "Pegamento", "Cinta adhesiva", "Grapadora", "Calculadora", "Moneda", "Billete", "Tarjeta de crédito", "Cartera", "Monedero", "Bolso", "Maleta", "Anillo", "Collar", "Pulsera", "Pendientes", "Sombrero", "Gorra", "Bufanda", "Guantes", "Zapatos", "Bicicleta", "Moto", "Autobús", "Tren", "Avión", "Barco", "Juguete", "Pelota", "Muñeca", "Videojuego", "Instrumento", "Guitarra", "Piano", "Violín", "Batería", "Flauta", "Trompeta"],
};

export const MYSTERY_WORD_CATEGORIES: { [key: string]: [string, string][] } = {
    "Aleatorio": [],
    "Comida": [
        ["Pasta", "Tomate"], ["Hamburguesa", "Parrilla"], ["Sushi", "Alga"], ["Pastel", "Vela"], ["Sopa", "Cuchara"],
        ["Pan", "Horno"], ["Queso", "Ratón"], ["Huevo", "Gallina"], ["Leche", "Vaca"], ["Miel", "Abeja"],
        ["Manzana", "Tarta"], ["Naranja", "Zumo"], ["Limón", "Ácido"], ["Plátano", "Mono"], ["Fresa", "Nata"],
        ["Uva", "Vino"], ["Sandía", "Verano"], ["Piña", "Tropical"], ["Aguacate", "Guacamole"], ["Tomate", "Ketchup"],
        ["Lechuga", "Ensalada"], ["Zanahoria", "Conejo"], ["Patata", "Frita"], ["Cebolla", "Llorar"], ["Ajo", "Vampiro"],
        ["Arroz", "Paella"], ["Frijol", "Refrito"], ["Lenteja", "Guiso"], ["Pollo", "Asado"], ["Pescado", "Mar"],
        ["Carne", "Bistec"], ["Huevo", "Frito"], ["Leche", "Cereal"], ["Queso", "Pizza"], ["Yogur", "Probiótico"],
        ["Mantequilla", "Tostada"], ["Pan", "Bocadillo"], ["Galleta", "Oreo"], ["Chocolate", "Tableta"], ["Helado", "Cucurucho"],
        ["Pastel", "Cumpleaños"], ["Dona", "Agujero"], ["Café", "Mañana"], ["Té", "Infusión"], ["Refresco", "Burbujas"],
        ["Agua", "Sed"], ["Cerveza", "Lúpulo"], ["Vino", "Corcho"], ["Pizza", "Italia"], ["Sushi", "Japón"],
        ["Taco", "México"], ["Paella", "España"], ["Croissant", "Francia"], ["Kebab", "Turquía"], ["Curry", "India"],
        ["Wok", "China"], ["Salchicha", "Alemania"], ["Palomitas", "Cine"], ["Nuez", "Cáscara"], ["Almendra", "Turrón"],
        ["Miel", "Colmena"], ["Azúcar", "Dulce"], ["Sal", "Salero"], ["Pimienta", "Pimentero"], ["Aceite", "Oliva"],
        ["Vinagre", "Encurtido"], ["Mostaza", "Hot-dog"], ["Mayonesa", "Sándwich"], ["Brócoli", "Árbol"], ["Pimiento", "Relleno"],
        ["Maíz", "Elote"], ["Champiñón", "Seta"], ["Espinaca", "Popeye"], ["Calabaza", "Halloween"], ["Espárrago", "Verde"],
        ["Alcachofa", "Corazón"], ["Berenjena", "Morado"], ["Remolacha", "Rojo"], ["Coliflor", "Blanco"], ["Guisante", "Vaina"],
        ["Garbanzo", "Hummus"], ["Aceituna", "Hueso"], ["Dátil", "Palmera"], ["Higo", "Breva"], ["Coco", "Agua"],
        ["Mango", "Hueso"], ["Papaya", "Semillas"], ["Kiwi", "Peludo"], ["Cereza", "Tallo"], ["Melocotón", "Piel"],
        ["Ciruela", "Pasa"], ["Albaricoque", "Orejón"], ["Frambuesa", "Roja"], ["Arándano", "Azul"], ["Mora", "Zarza"]
    ],
    "Animales": [
        ["León", "Sabana"], ["Tiburón", "Aleta"], ["Abeja", "Panal"], ["Camello", "Oasis"], ["Serpiente", "Veneno"],
        ["Perro", "Correa"], ["Gato", "Lana"], ["Pájaro", "Nido"], ["Pez", "Anzuelo"], ["Caballo", "Establo"],
        ["Elefante", "Trompa"], ["Jirafa", "Cuello"], ["Tigre", "Rayas"], ["Oso", "Invernar"], ["Pingüino", "Hielo"],
        ["Delfín", "Salto"], ["Ballena", "Chorro"], ["Mono", "Plátano"], ["Loro", "Hablar"], ["Búho", "Noche"],
        ["Rana", "Charca"], ["Mariposa", "Oruga"], ["Vaca", "Mugir"], ["Cerdo", "Lodo"], ["Oveja", "Lana"],
        ["Cabra", "Barba"], ["Gallina", "Cacarear"], ["Pato", "Estanque"], ["Conejo", "Zanahoria"], ["Ratón", "Queso"],
        ["Ardilla", "Nuez"], ["Zorro", "Astuto"], ["Lobo", "Aullar"], ["Ciervo", "Cornamenta"], ["Hipopótamo", "Río"],
        ["Rinoceronte", "Cuerno"], ["Cocodrilo", "Lágrima"], ["Tortuga", "Caparazón"], ["Koala", "Eucalipto"], ["Canguro", "Bolsa"],
        ["Panda", "Bambú"], ["Gorila", "Pecho"], ["Murciélago", "Cueva"], ["Erizo", "Púas"], ["Castor", "Presa"],
        ["Nutria", "Piedra"], ["Morsa", "Colmillos"], ["Foca", "Aplauso"], ["Leopardo", "Manchas"], ["Hiena", "Risa"],
        ["Llama", "Escupir"], ["Armadillo", "Bola"], ["Perezoso", "Lento"], ["Tucán", "Pico"], ["Colibrí", "Néctar"],
        ["Flamenco", "Rosa"], ["Cisne", "Lago"], ["Águila", "Nido"], ["Cuervo", "Graznar"], ["Paloma", "Paz"],
        ["Avestruz", "Huevo"], ["Pulpo", "Tinta"], ["Calamar", "Gigante"], ["Medusa", "Picadura"], ["Estrella de mar", "Cinco"],
        ["Cangrejo", "Pinzas"], ["Langosta", "Roja"], ["Caracol", "Baba"], ["Gusano", "Tierra"], ["Araña", "Telaraña"],
        ["Escorpión", "Aguijón"], ["Avispa", "Picotazo"], ["Hormiga", "Hormiguero"], ["Mosca", "Zumbido"], ["Mosquito", "Sangre"],
        ["Libélula", "Helicóptero"], ["Grillo", "Canto"], ["Saltamontes", "Salto"], ["Cebra", "Paso"], ["Guepardo", "Veloz"],
        ["Camaleón", "Color"], ["Pavo real", "Cola"], ["Cacatúa", "Cresta"], ["Orangután", "Selva"], ["Chimpancé", "Herramienta"],
        ["Iguana", "Sol"], ["Suricata", "Vigía"], ["Topo", "Túnel"], ["Alce", "Canadá"], ["Bisonte", "Manada"],
        ["Búfalo", "Agua"], ["Gacela", "Correr"], ["Antílope", "Salto"], ["Halcón", "Presa"], ["Pelícano", "Bolsa"]
    ],
    "Lugares": [
        ["Cine", "Entrada"], ["Hospital", "Bisturí"], ["Biblioteca", "Silencio"], ["Iglesia", "Campana"], ["Supermercado", "Carrito"],
        ["Escuela", "Pizarra"], ["Playa", "Arena"], ["Bosque", "Árbol"], ["Montaña", "Nieve"], ["Desierto", "Cactus"],
        ["Oficina", "Escritorio"], ["Restaurante", "Menú"], ["Parque", "Columpio"], ["Museo", "Cuadro"], ["Aeropuerto", "Avión"],
        ["Estación", "Tren"], ["Gimnasio", "Pesa"], ["Teatro", "Escenario"], ["Banco", "Dinero"], ["Granja", "Tractor"],
        ["Fábrica", "Chimenea"], ["Castillo", "Rey"], ["Puerto", "Barco"], ["Universidad", "Diploma"], ["Farmacia", "Medicina"],
        ["Tienda", "Comprar"], ["Centro comercial", "Escaleras"], ["Cementerio", "Tumba"], ["Estadio", "Grada"], ["Piscina", "Cloro"],
        ["Zoológico", "Jaula"], ["Acuario", "Pecera"], ["Jardín", "Flor"], ["Plaza", "Fuente"], ["Calle", "Semáforo"],
        ["Carretera", "Coche"], ["Puente", "Río"], ["Túnel", "Oscuro"], ["Isla", "Palmera"], ["Volcán", "Lava"],
        ["Cueva", "Murciélago"], ["Cascada", "Agua"], ["Río", "Corriente"], ["Lago", "Barca"], ["Mar", "Olas"],
        ["Océano", "Profundo"], ["Glaciar", "Hielo"], ["Selva", "Liana"], ["Pantano", "Cocodrilo"], ["Casa", "Hogar"],
        ["Apartamento", "Piso"], ["Hotel", "Habitación"], ["Palacio", "Reina"], ["Prisión", "Celda"], ["Cuartel", "Soldado"],
        ["Embajada", "Bandera"], ["Tribunal", "Juez"], ["Laboratorio", "Probeta"], ["Observatorio", "Telescopio"], ["Planetario", "Estrellas"],
        ["Galería", "Escultura"], ["Ópera", "Aria"], ["Circo", "Payaso"], ["Feria", "Noria"], ["Discoteca", "Música"],
        ["Bar", "Bebida"], ["Cafetería", "Café"], ["Panadería", "Pan"], ["Pastelería", "Tarta"], ["Carnicería", "Carne"],
        ["Pescadería", "Pescado"], ["Mercado", "Puesto"], ["Peluquería", "Tijeras"], ["Taller", "Herramienta"], ["Garaje", "Aparcar"],
        ["Gasolinera", "Gasolina"], ["Pirámide", "Egipto"], ["Muralla", "China"], ["Coliseo", "Roma"], ["Torre Eiffel", "París"],
        ["Estatua de la Libertad", "Nueva York"], ["Taj Mahal", "India"], ["Acrópolis", "Grecia"], ["Machu Picchu", "Perú"], ["Rascacielos", "Altura"],
        ["Faro", "Luz"], ["Molino", "Viento"], ["Viñedo", "Uva"], ["Salina", "Sal"], ["Mina", "Pico"],
        ["Cantera", "Piedra"], ["Pozo", "Agua"], ["Oasis", "Palmera"], ["Arrecife", "Coral"], ["Géiser", "Vapor"]
    ],
    "Profesiones": [
        ["Astronauta", "Gravedad"], ["Científico", "Laboratorio"], ["Carpintero", "Martillo"], ["Fotógrafo", "Lente"], ["Mago", "Varita"],
        ["Médico", "Estetoscopio"], ["Bombero", "Manguera"], ["Policía", "Esposas"], ["Profesor", "Tiza"], ["Piloto", "Avión"],
        ["Profesor", "Pizarra"], ["Ingeniero", "Plano"], ["Artista", "Pincel"], ["Chef", "Sartén"], ["Abogado", "Ley"],
        ["Actor", "Guion"], ["Músico", "Partitura"], ["Escritor", "Libro"], ["Pintor", "Lienzo"], ["Deportista", "Medalla"],
        ["Periodista", "Noticia"], ["Juez", "Mazo"], ["Mecánico", "Llave"], ["Veterinario", "Mascota"], ["Enfermero", "Inyección"],
        ["Dentista", "Muela"], ["Farmacéutico", "Receta"], ["Psicólogo", "Terapia"], ["Arquitecto", "Edificio"], ["Diseñador", "Boceto"],
        ["Programador", "Código"], ["Contador", "Impuestos"], ["Gerente", "Reunión"], ["Secretario", "Agenda"], ["Traductor", "Idioma"],
        ["Guía turístico", "Monumento"], ["Azafata", "Vuelo"], ["Marino", "Ancla"], ["Soldado", "Uniforme"], ["Detective", "Lupa"],
        ["Guardia", "Vigilar"], ["Salvavidas", "Flotador"], ["Albañil", "Ladrillo"], ["Electricista", "Cable"], ["Fontanero", "Tubería"],
        ["Jardinero", "Planta"], ["Agricultor", "Cosecha"], ["Pescador", "Red"], ["Minero", "Carbón"], ["Panadero", "Harina"],
        ["Carnicero", "Cuchillo"], ["Cajero", "Caja"], ["Vendedor", "Cliente"], ["Empresario", "Negocio"], ["Banquero", "Préstamo"],
        ["Camarero", "Bandeja"], ["Barman", "Cóctel"], ["Camarógrafo", "Grabar"], ["Director de cine", "Cámara"], ["Editor", "Montaje"],
        ["Maquillador", "Pintalabios"], ["Peluquero", "Peine"], ["Estilista", "Ropa"], ["Modelo", "Pasarela"], ["Bailarín", "Ballet"],
        ["Cantante", "Micrófono"], ["Compositor", "Nota"], ["DJ", "Mesa"], ["Poeta", "Verso"], ["Escultor", "Arcilla"],
        ["Filósofo", "Pensar"], ["Biólogo", "Célula"], ["Químico", "Elemento"], ["Físico", "Átomo"], ["Geólogo", "Roca"],
        ["Meteorólogo", "Clima"], ["Historiador", "Pasado"], ["Arqueólogo", "Ruina"], ["Político", "Voto"], ["Espía", "Secreto"],
        ["Ladrón", "Robar"], ["Payaso", "Nariz"], ["Acróbata", "Trapecio"], ["Presentador", "Televisión"], ["Locutor", "Radio"],
        ["Influencer", "Redes"], ["Youtuber", "Video"], ["Taxista", "Taxi"], ["Conductor", "Autobús"], ["Mensajero", "Paquete"]
    ],
    "Deportes": [
        ["Boxeo", "Ring"], ["Fútbol", "Portería"], ["Natación", "Piscina"], ["Tenis", "Raqueta"], ["Golf", "Hoyo"],
        ["Baloncesto", "Canasta"], ["Béisbol", "Bate"], ["Ciclismo", "Bicicleta"], ["Voleibol", "Red"], ["Atletismo", "Pista"],
        ["Esquí", "Nieve"], ["Surf", "Ola"], ["Patinaje", "Hielo"], ["Lucha", "Llave"], ["Gimnasia", "Salto"],
        ["Karate", "Cinturón"], ["Esgrima", "Espada"], ["Tiro con arco", "Flecha"], ["Halterofilia", "Pesa"], ["Yoga", "Postura"],
        ["Skateboarding", "Tabla"], ["Automovilismo", "Circuito"], ["Vela", "Viento"], ["Remo", "Remos"], ["Piragüismo", "Pala"],
        ["Buceo", "Oxígeno"], ["Waterpolo", "Gorro"], ["Triatlón", "Tres"], ["Maratón", "Correr"], ["Salto de altura", "Barra"],
        ["Lanzamiento de peso", "Bola"], ["Lanzamiento de jabalina", "Lanza"], ["Balonmano", "Gol"], ["Fútbol americano", "Touchdown"], ["Lacrosse", "Stick"],
        ["Polo", "Caballo"], ["Equitación", "Silla"], ["Bádminton", "Volante"], ["Squash", "Pared"], ["Pádel", "Cristal"],
        ["Tenis de mesa", "Ping-pong"], ["Billar", "Taco"], ["Bolos", "Pinos"], ["Dardos", "Diana"], ["Ajedrez", "Jaque"],
        ["Póker", "Ficha"], ["Escalada", "Arnés"], ["Alpinismo", "Cima"], ["Senderismo", "Mochila"], ["Parkour", "Obstáculo"],
        ["Paracaidismo", "Avión"], ["Rugby", "Melé"], ["Hockey", "Puck"], ["Críquet", "Bateador"], ["Taekwondo", "Patada"],
        ["Judo", "Tatami"], ["Sumo", "Dohyō"], ["Crossfit", "WOD"], ["Pilates", "Reformer"], ["Baile", "Ritmo"],
        ["BMX", "Rampa"], ["Motocross", "Salto"], ["Rally", "Etapa"], ["Fórmula 1", "Monoplaza"], ["Kitesurf", "Cometa"],
        ["Windsurf", "Vela"], ["Apnea", "Pulmón"], ["Nado sincronizado", "Coreografía"], ["Salto ornamental", "Trampolín"], ["Pentatlón", "Moderno"],
        ["Decatlón", "Diez"], ["Carrera de vallas", "Obstáculo"], ["Salto con pértiga", "Garrocha"], ["Salto de longitud", "Foso"], ["Lanzamiento de disco", "Jaula"],
        ["Lanzamiento de martillo", "Giro"], ["Fútbol sala", "Futsal"], ["Fútbol playa", "Arena"], ["Patinaje de velocidad", "Óvalo"], ["Patinaje artístico", "Pirueta"],
        ["Curling", "Piedra"], ["Bobsleigh", "Trineo"], ["Snowboard", "Tabla"], ["Esquí de fondo", "Resistencia"], ["Salto de esquí", "Trampolín"],
        ["Biatlón", "Disparo"], ["Softbol", "Guante"], ["Ultimate frisbee", "Disco"], ["Tiro", "Pistola"], ["Carreras de caballos", "Jinete"]
    ],
    "Objetos": [
        ["Cámara", "Foto"], ["Libro", "Página"], ["Guitarra", "Cuerda"], ["Candado", "Llave"], ["Reloj", "Tiempo"],
        ["Teléfono", "Llamada"], ["Silla", "Sentarse"], ["Mesa", "Comer"], ["Coche", "Rueda"], ["Cama", "Dormir"],
        ["Silla", "Pata"], ["Mesa", "Tablero"], ["Cama", "Colchón"], ["Sofá", "Cojín"], ["Armario", "Percha"],
        ["Escritorio", "Cajón"], ["Puerta", "Pomo"], ["Ventana", "Cristal"], ["Lámpara", "Bombilla"], ["Espejo", "Reflejo"],
        ["Tijeras", "Cortar"], ["Martillo", "Clavar"], ["Tornillo", "Girar"], ["Clavo", "Pared"], ["Cepillo", "Pelo"],
        ["Peine", "Dientes"], ["Vaso", "Beber"], ["Plato", "Comida"], ["Tenedor", "Pinchar"], ["Cuchillo", "Filo"],
        ["Cuchara", "Sopa"], ["Olla", "Tapa"], ["Sartén", "Freír"], ["Nevera", "Frío"], ["Horno", "Calor"],
        ["Microondas", "Ondas"], ["Lavadora", "Ropa"], ["Televisión", "Pantalla"], ["Radio", "Antena"], ["Teléfono", "Marcar"],
        ["Ordenador", "Teclado"], ["Ratón", "Clic"], ["Impresora", "Tinta"], ["Auriculares", "Oído"], ["Mochila", "Espalda"],
        ["Maleta", "Viaje"], ["Paraguas", "Lluvia"], ["Gafas", "Ver"], ["Llave", "Cerradura"], ["Bolígrafo", "Escribir"],
        ["Lápiz", "Mina"], ["Cuaderno", "Apuntes"], ["Goma de borrar", "Corregir"], ["Regla", "Medir"], ["Pegamento", "Pegar"],
        ["Grapadora", "Grapa"], ["Anillo", "Dedo"], ["Collar", "Cuello"], ["Pulsera", "Muñeca"], ["Sombrero", "Cabeza"],
        ["Zapato", "Pie"], ["Bicicleta", "Pedal"], ["Moto", "Manillar"], ["Coche", "Volante"], ["Autobús", "Parada"],
        ["Tren", "Vía"], ["Avión", "Ala"], ["Barco", "Proa"], ["Pelota", "Bote"], ["Juguete", "Niño"],
        ["Piano", "Tecla"], ["Violín", "Arco"], ["Batería", "Baqueta"], ["Flauta", "Agujero"], ["Trompeta", "Pistón"],
        ["Escoba", "Barrer"], ["Fregona", "Mojar"], ["Cubo", "Agua"], ["Papelera", "Basura"], ["Bombilla", "Luz"],
        ["Vela", "Fuego"], ["Pila", "Energía"], ["Cable", "Enchufe"], ["Revista", "Artículo"], ["Periódico", "Noticia"],
        ["Mapa", "Ruta"], ["Brújula", "Norte"], ["Globo", "Aire"], ["Cometa", "Volar"], ["Dado", "Número"]
    ],
};

export const MIN_PLAYERS = 3;
export const MAX_PLAYERS = 10;
